---
- name: Converge
  hosts: bbb
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    bbb_nodejs_version: 8.x
    bbb_letsencrypt_enable: false
    bbb_letsencrypt_email: mail@example.com
  tasks:
    - name: "Include n0emis.bigbluebutton"
      include_role:
        name: "n0emis.bigbluebutton"
